dubbo:
  application:
    name: ego-passport
  registry:
    address: zookeeper://192.168.64.4:2181

server:
  port: 8084

# Spring MVC视图解析器
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  profiles:
    active: commons,redis